#!/usr/bin/env python3
"""
notify.py - Weekly digest email of all blog posts published in the last 7 days.

IMPORTANT: this NEVER touches the lead form worker (braza-email-proxy). Blog
notifications use their OWN Resend channel so lead inbox + conversion metrics
stay clean. If RESEND_API_KEY is not set, it prints the digest and exits 0
(no email) instead of falling back to the lead worker.

Backed by automation/published_log.json, appended by update_site.py on each
publish: [{slug, title, url, date, category}].

Usage:
  py automation/notify.py --weekly [--dry]     # send/print the weekly digest
  py automation/notify.py --log <slug>         # (internal) append a post to the log
"""
import sys, os, io, re, json, urllib.request, datetime

# force UTF-8 stdout on Windows so non-ascii never crashes
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG = os.path.join(ROOT, 'automation', 'published_log.json')
TO = 'brazacleaningservices@gmail.com'
FROM = 'Braza Blog <website@brazacleaning.com>'

def load_log():
    return json.load(open(LOG, encoding='utf-8')) if os.path.isfile(LOG) else []

def grab(s, pat, flags=re.I | re.S):
    m = re.search(pat, s, flags); return m.group(1).strip() if m else ''

def log_post(slug):
    """Append a published post to the log (idempotent on slug+date)."""
    path = os.path.join(ROOT, 'blog', slug, 'index.html')
    h = open(path, encoding='utf-8').read()
    title = re.sub(r'<[^>]+>', '', grab(h, r'<h1[^>]*>(.*?)</h1>')).strip()
    date = grab(h, r'"datePublished"\s*:\s*"([^"]+)"')
    cat = grab(h, r'<span class="blog-cat">(.*?)</span>')
    entry = dict(slug=slug, title=title, url=f'https://brazacleaning.com/blog/{slug}/',
                 date=date, category=re.sub(r'<[^>]+>', '', cat).strip())
    log = [e for e in load_log() if not (e['slug'] == slug and e['date'] == date)]
    log.append(entry)
    json.dump(log, open(LOG, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
    print(f'logged: {slug} ({date})')

def recent(days=7):
    today = datetime.date.fromisoformat(os.environ.get('TODAY') or datetime.date.today().isoformat())
    cutoff = today - datetime.timedelta(days=days)
    out = []
    for e in load_log():
        try:
            d = datetime.date.fromisoformat(e['date'])
        except Exception:
            continue
        if d >= cutoff:
            out.append(e)
    return sorted(out, key=lambda e: e['date'], reverse=True)

def weekly(dry=False):
    posts = recent(7)
    if not posts:
        print('Nenhum post nos ultimos 7 dias — digest nao enviado.')
        return
    rows = ''.join(
        f'<tr><td style="padding:10px 14px;border-bottom:1px solid #E5E7EB">'
        f'<a href="{p["url"]}" style="color:#2B6CB0;font-weight:600;text-decoration:none">{p["title"]}</a>'
        f'<div style="color:#6B7280;font-size:12px;margin-top:2px">{p["category"]} · {p["date"]}</div></td></tr>'
        for p in posts)
    subject = f'Braza Blog — {len(posts)} new posts this week'
    body = (f'<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px">'
            f'<h2 style="color:#2B6CB0">This week on the Braza blog</h2>'
            f'<p style="color:#374151">{len(posts)} post(s) published in the last 7 days:</p>'
            f'<table style="width:100%;border-collapse:collapse;border:1px solid #E5E7EB">{rows}</table>'
            f'<p style="color:#6B7280;font-size:12px;margin-top:16px">Auto-generated by the Braza blog pipeline. '
            f'This channel is separate from website leads.</p></div>')

    print(f'DIGEST: {len(posts)} post(s) — {subject}')
    for p in posts:
        print(f'  - {p["date"]}  {p["title"]}')
    if dry:
        print('DRY-RUN — email NAO enviado.'); return

    key = os.environ.get('RESEND_API_KEY')
    if not key:
        print('RESEND_API_KEY ausente — digest impresso acima, mas NAO enviado '
              '(nao uso o worker de leads de proposito).')
        return
    data = json.dumps({'from': FROM, 'to': [TO], 'subject': subject, 'html': body}).encode()
    req = urllib.request.Request('https://api.resend.com/emails', data=data, method='POST',
                                 headers={'Content-Type': 'application/json',
                                          'Authorization': f'Bearer {key}'})
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            print(f'digest enviado (HTTP {r.status})')
    except Exception as e:
        print('FALHA ao enviar digest:', e); sys.exit(1)

def main():
    a = sys.argv[1:]
    if not a:
        sys.exit('uso: notify.py --weekly [--dry]  |  notify.py --log <slug>')
    if a[0] == '--log' and len(a) > 1:
        log_post(a[1])
    elif a[0] == '--weekly':
        weekly(dry='--dry' in a)
    else:
        sys.exit('flag desconhecida. use --weekly ou --log <slug>')

if __name__ == '__main__':
    main()
